sudo: required
services:
  - docker

before_install:
  - docker build -t kevinwallimann/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kevinwallimann/react-test npm test

after_success:
  - docker build -t kevinwallimann/multi-client ./client
  - docker build -t kevinwallimann/multi-nginx ./nginx
  - docker build -t kevinwallimann/multi-server ./server
  - docker build -t kevinwallimann/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push kevinwallimann/multi-client
  - docker push kevinwallimann/multi-nginx
  - docker push kevinwallimann/multi-server
  - docker push kevinwallimann/multi-worker
    #
    #deploy:
    #  provider: elasticbeanstalk
    #  region: us-east-2
    #  app: multi-docker
    #  env: MultiDocker-env
    #  bucket_name: elasticbeanstalk-us-east-2-306476627547
    #  bucket_path: docker-multi
    #  on:
    #    branch: master
    #  access_key_id: $AWS_ACCESS_KEY
    #  secret_access_key:
    #    secure: $AWS_SECRET_KEY
